global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "strategy_rules.yml"

scrape_configs:
  - job_name: 'meteora-strategy'
    static_configs:
      - targets: ['meteora-strategy:3000']
    scrape_interval: 5s
    metrics_path: '/metrics'
    
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093 